name: Swift Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Swift Package
        run: swift build
      - name: Run Tests
        run: swift test 